# Site settings
title: Preeti Ravindra
description: 'Webpage of Preeti Ravindra'
url: 'http://thomas.zuehlke.family'
baseurl: ''
profilepic: '/images/preetir.jpeg'
bkimage: '/images/bktrial04.jpeg'
google_analytics:
font_awesome: 'fontawesome/js/all.js'

author:
  name: 'Preeti Ravindra'
  email:
  twitter_username: emerging_cyber
  facebook_username:
  github_username:  emergingcyber
  linkedin_username:  preeti-ravindra
  meetup_name:
  medium_name:

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
