baseURL = 'https://preetiravindra.info'
languageCode = 'en-us'
title = 'Preeti Ravindra'
theme = 'dimension'

# Ignore scripts directory from Hugo processing
ignoreFiles = ['^scripts/']

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.8
